config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :schemes do
      resources :scheme_tiles
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :houses, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  include FriendlyId
  friendly_id :name

  has_many :rooms, dependent: :destroy

  def ground_floor_rooms
    rooms.select{ |r| r.ground_floor? }
  end

  def upper_floor_rooms
    rooms.select{ |r| !r.ground_floor? }
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :house
  has_and_belongs_to_many :schemes
end

app/models/scheme.rb
class Scheme < ApplicationRecord
  has_and_belongs_to_many :rooms
  has_many :scheme_tiles
end

app/models/scheme_tile.rb
class SchemeTile < ApplicationRecord
  belongs_to :tile
  belongs_to :scheme

  scope :wall,    -> { where( surface: 'wall'    ) }
  scope :feature, -> { where( surface: 'feature' ) }
  scope :floor,   -> { where( surface: 'floor'   ) }
end

app/models/tile.rb
class Tile < ApplicationRecord
  has_and_belongs_to_many :schemes
end

app/controllers/admin/scheme_tiles_controller.rb
class Admin::SchemeTilesController < ApplicationController

  before_action :load_scheme, only:[ :show, :edit, :update, :destroy ]

  def index
    @tiles = Tiles.all.order :name
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destory
  end

  private
  def load_scheme 
    @scheme = Scheme.find params[:id]
  end
end

app/controllers/admin/schemes_controller.rb
class Admin::SchemesController < ApplicationController

  before_action :load_scheme, only:[ :show, :edit, :update, :destroy ]

  def index
    @schemes = Scheme.all.order :name
  end

  def new
    @scheme = Scheme.new
  end

  def create
    @scheme = Scheme.new( scheme_params )
    @scheme.save
  end

  def update
    @scheme.update scheme_params
    render :show
  end

  def destroy
    @scheme.destroy
    redirect_to :index
  end

  private
  def scheme_params
    params.require( :scheme ).permit( :name )
  end

  def load_scheme 
    @scheme = Scheme.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @houses = House.all.order :name
  end

  def show
    @house = House.friendly.find params[:id]
  end

end

app/helpers/admin/scheme_tiles_helper.rb
module Admin::SchemeTilesHelper
end

app/helpers/admin/schemes_helper.rb
module Admin::SchemesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/admin/scheme_tiles/create.html.haml
%h1 Admin::SchemeTiles#create
%p Find me in app/views/admin/scheme_tiles/create.html.haml

app/views/admin/scheme_tiles/destory.html.haml
%h1 Admin::SchemeTiles#destory
%p Find me in app/views/admin/scheme_tiles/destory.html.haml

app/views/admin/scheme_tiles/edit.html.haml
%h1 Admin::SchemeTiles#edit
%p Find me in app/views/admin/scheme_tiles/edit.html.haml

app/views/admin/scheme_tiles/index.html.haml
%h1 Admin::SchemeTiles#index
%p Find me in app/views/admin/scheme_tiles/index.html.haml

app/views/admin/scheme_tiles/new.html.haml
%h1 Admin::SchemeTiles#new
%p Find me in app/views/admin/scheme_tiles/new.html.haml

app/views/admin/scheme_tiles/show.html.haml
%h1 Admin::SchemeTiles#show
%p Find me in app/views/admin/scheme_tiles/show.html.haml

app/views/admin/scheme_tiles/update.html.haml
%h1 Admin::SchemeTiles#update
%p Find me in app/views/admin/scheme_tiles/update.html.haml

app/views/admin/schemes/_form.html.haml
= form_for [:admin, @scheme] do |f|
  = f.label :name
  = f.text_field :name

  = yield

  = f.submit 

app/views/admin/schemes/create.html.haml
%h1 Admin::Schemes#create
%p Find me in app/views/admin/schemes/create.html.haml

app/views/admin/schemes/destroy.html.haml
%h1 Admin::Schemes#destory
%p Find me in app/views/admin/schemes/destory.html.haml

app/views/admin/schemes/edit.html.haml
%h1 Admin::Schemes#edit

= render partial: 'form' 

app/views/admin/schemes/index.html.haml
%h1 Admin::Schemes#index

%ul
  - @schemes.each do |s|
    %li= link_to( s.name, admin_scheme_path( s ) )

app/views/admin/schemes/new.html.haml
%h1 Admin::Schemes#new

= render partial: 'form'

app/views/admin/schemes/show.html.haml
%h1 Admin::Schemes#show

%p= @scheme.name

%p= link_to 'Edit', edit_admin_scheme_path( @scheme )


%p= link_to 'Change tile options', admin_scheme_scheme_tiles_path( @scheme )

app/views/admin/schemes/update.html.haml
%h1 Admin::Schemes#update
%p Find me in app/views/admin/schemes/update.html.haml

app/views/houses/index.html.haml
%ul
  - @houses.each do |h|
    %li= link_to( h.name, house_path( h ) )

app/views/houses/show.html.haml
%p= @house.name

%p Ground floor rooms

%ul
  - @house.ground_floor_rooms.each do |r|
    %li= r.name

%p Upper floor rooms

%ul
  - @house.upper_floor_rooms.each do |r|
    %li= r.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tilecutter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield